### ISSUE TITLE
Error with translation during vocabulary import

### ISSUE THREAD

**Issue by RAG2ko** [prz3m/kind2anki#2]
Hi,

I was trying to import vocabulary from my kindle using the translation option when the following error occurred:

>Traceback (most recent call last):
  File "C:\Users\phili\Documents\Anki\addons\kind2anki\__init__.py", line 56, in accept
    kindleImporter.translateWordsFromDB()
  File "C:\Users\phili\Documents\Anki\addons\kind2anki\kindleimporter.py", line 22, in translateWordsFromDB
    self.translated = self.translateWords()
  File "C:\Users\phili\Documents\Anki\addons\kind2anki\kindleimporter.py", line 56, in translateWords
    except textblob.exceptions.NotTranslated:
NameError: global name 'textblob' is not defined

The words are a mix of German, English and Spanish. I tried translating to different languages but the error is always the same. If I deactivate the translation option, the import works fine.

Any idea what might be the problem?

THX.

**Comment by prz3m** [comment]
I'll take a look soon!

**Comment by prz3m** [comment]
Ok, I've forgotten to properly clean up after changing library. I changed `except textblob.exceptions.NotTranslated:` to `except:` :) Now it should work.

However, I admit that results can be sometimes not acceptable. The addon uses http://mymemory.translated.net/ (because Google Translate is no longer available for free) which is not that cool. It doesn't have language detection, so the addon assumes that everything is in english :/
It would be the best to switch to some offline dictionary, but again, language detection will not work. Maybe in future I will do something with it.

**Comment by prz3m** [comment]
Ok, I found transltr.org, it works fine and have language detection.

**Comment by RAG2ko** [comment]
Great, THX!
